const productData = [
  {
    id: 1,
    name: "Advanced Night Repair",
    brand: "Estée Lauder",
    type: "Zardob (Serum)",
    category: "Skin Care",
    description: "Teringizni tungi vaqtda chuqur tiklovchi va ajinlarni kamaytiruvchi premium zardob.",
    price: 105,
    oldPrice: 150,
    discount: 30,
    isNew: false,
    rating: 4.9,
    stock: 8,
    sold: 92,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=600&auto=format&fit=crop",
    tags: ["Trending", "AI Choice"]
  },
  {
    id: 2,
    name: "Matte Revolution",
    brand: "Charlotte Tilbury",
    type: "Lab bo'yog'i",
    category: "Makeup",
    description: "Uzoq vaqt saqlanib turuvchi, lablarni quritmaydigan mot teksturali lab bo'yog'i.",
    price: 35,
    oldPrice: 45,
    discount: 22,
    isNew: true,
    rating: 4.8,
    stock: 15,
    sold: 45,
    image: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?q=80&w=600&auto=format&fit=crop",
    tags: ["New Collection"]
  },
  {
    id: 3,
    name: "Hydrating Cleanser",
    brand: "CeraVe",
    type: "Tozalovchi gel",
    category: "Skin Care",
    description: "Normal va quruq teri uchun mo'ljallangan, namlikni saqlovchi yumshoq tozalovchi.",
    price: 18,
    oldPrice: 22,
    discount: 18,
    isNew: false,
    rating: 4.7,
    stock: 50,
    sold: 80,
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=600&auto=format&fit=crop",
    tags: ["Best Seller"]
  },
  {
    id: 4,
    name: "Black Opium EDP",
    brand: "YSL",
    type: "Atir (Fragrance)",
    category: "Perfume",
    description: "Sharqona va shirin iforga ega, ayollar uchun mo'ljallangan mashhur parfyum.",
    price: 130,
    oldPrice: 160,
    discount: 18,
    isNew: true,
    rating: 5.0,
    stock: 4,
    sold: 96,
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=600&auto=format&fit=crop",
    tags: ["Luxury", "AI Choice"]
  },
  {
    id: 5,
    name: "Niacinamide 10%",
    brand: "The Ordinary",
    type: "Zardob",
    category: "Skin Care",
    description: "Yog'li terini nazorat qilish va poralarni kichraytirish uchun samarali vosita.",
    price: 12,
    oldPrice: 15,
    discount: 20,
    isNew: false,
    rating: 4.6,
    stock: 100,
    sold: 70,
    image: "https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=600&auto=format&fit=crop",
    tags: ["Trending"]
  },
  {
    id: 6,
    name: "Watermelon Glow",
    brand: "Glow Recipe",
    type: "Namlantiruvchi",
    category: "Skin Care",
    description: "Teringizga tabiiy yorqinlik beruvchi va namlantiruvchi tarvuzli krem.",
    price: 39,
    oldPrice: 48,
    discount: 18,
    isNew: true,
    rating: 4.7,
    stock: 12,
    sold: 60,
    image: "https://images.unsplash.com/photo-1620917670397-dc7bc45e6976?q=80&w=600&auto=format&fit=crop",
    tags: ["New", "Trending"]
  },
  {
    id: 7,
    name: "Sauvage Parfum",
    brand: "Dior",
    type: "Atir",
    category: "Perfume",
    price: 95,
    oldPrice: 110,
    discount: 15,
    isNew: false,
    rating: 4.9,
    stock: 6,
    sold: 88,
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?q=80&w=600&auto=format&fit=crop",
    tags: ["Best Seller"]
  },
  {
    id: 8,
    name: "Radiant Concealer",
    brand: "NARS",
    type: "Konsiler",
    category: "Makeup",
    description: "Teri nuqsonlarini mukammal yashiruvchi va yorqinlik beruvchi professional konsiler.",
    price: 32,
    oldPrice: 40,
    discount: 20,
    isNew: false,
    rating: 4.8,
    stock: 25,
    sold: 55,
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=600&auto=format&fit=crop",
    tags: ["Professional"]
  },
  {
    id: 9,
    name: "Lip Sleeping Mask",
    brand: "Laneige",
    type: "Lab parvarishi",
    category: "Skin Care",
    description: "Tungi vaqtda lablarni oziqlantiruvchi va yumshatuvchi vitaminli maska.",
    price: 24,
    oldPrice: 30,
    discount: 20,
    isNew: false,
    rating: 4.9,
    stock: 3,
    sold: 98,
    image: "https://images.unsplash.com/photo-1591360236630-4eb9b3c44a1b?q=80&w=600&auto=format&fit=crop",
    tags: ["Viral", "AI Choice"]
  },
  {
    id: 10,
    name: "Pro Filt'r Foundation",
    brand: "Fenty Beauty",
    type: "Tonal krem",
    category: "Makeup",
    description: "Rihanna'dan barcha teri ranglariga mos keluvchi uzoq chidamli tonal krem.",
    price: 40,
    oldPrice: 50,
    discount: 20,
    isNew: true,
    rating: 4.7,
    stock: 20,
    sold: 40,
    image: "https://images.unsplash.com/photo-1599733594230-6b823276abcc?q=80&w=600&auto=format&fit=crop",
    tags: ["Trending"]
  },
  {
    id: 11,
    name: "Crème de la Mer",
    brand: "La Mer",
    type: "Premium Krem",
    category: "Skin Care",
    description: "Dunyodagi eng mashhur va boy tarkibli tiklovchi premium yuz kremi.",
    price: 190,
    oldPrice: 240,
    discount: 20,
    isNew: false,
    rating: 5.0,
    stock: 2,
    sold: 95,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=600&auto=format&fit=crop",
    tags: ["Luxury"]
  },
  {
    id: 12,
    name: "Bum Bum Cream",
    brand: "Sol de Janeiro",
    type: "Tana kremi",
    category: "Body Care",
    description: "Tana terisini taranglashtiruvchi va ajoyib tropik ifor taratuvchi krem.",
    price: 48,
    oldPrice: 55,
    discount: 12,
    isNew: true,
    rating: 4.8,
    stock: 18,
    sold: 72,
    image: "https://images.unsplash.com/photo-1624454002302-36b824d7bd0a?q=80&w=600&auto=format&fit=crop",
    tags: ["Viral"]
  },
  {
    id: 13,
    name: "Rose Quartz Palette",
    brand: "Huda Beauty",
    type: "Tenlar paletkasi",
    category: "Makeup",
    description: "18 xil yorqin va mot ranglarni o'z ichiga olgan ko'z tenlari to'plami.",
    price: 65,
    oldPrice: 80,
    discount: 18,
    isNew: false,
    rating: 4.9,
    stock: 7,
    sold: 85,
    image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=600&auto=format&fit=crop",
    tags: ["Premium"]
  },
  {
    id: 14,
    name: "No. 3 Hair Perfector",
    brand: "Olaplex",
    type: "Soch maskasi",
    category: "Hair Care",
    description: "Zararlangan soch tolalarini ichidan tiklovchi professional vosita.",
    price: 30,
    oldPrice: 38,
    discount: 21,
    isNew: false,
    rating: 4.7,
    stock: 45,
    sold: 65,
    image: "https://images.unsplash.com/photo-1527799822367-a2886701f552?q=80&w=600&auto=format&fit=crop",
    tags: ["Best Seller"]
  },
  {
    id: 15,
    name: "The Dewy Skin Cream",
    brand: "Tatcha",
    type: "Yuz kremi",
    category: "Skin Care",
    description: "Yapon an'analari asosida yaratilgan, terini shishasimon yorqin qiluvchi krem.",
    price: 70,
    oldPrice: 85,
    discount: 17,
    isNew: true,
    rating: 4.9,
    stock: 10,
    sold: 50,
    image: "https://images.unsplash.com/photo-1590156546746-7d08ef355030?q=80&w=600&auto=format&fit=crop",
    tags: ["AI Choice"]
  },
  {
    id: 16,
    name: "Baccarat Rouge 540",
    brand: "MFK",
    type: "Atir",
    category: "Perfume",
    description: "Dunyoning eng hashamatli va tanib olinadigan amber-gulli ifori.",
    price: 325,
    oldPrice: 380,
    discount: 14,
    isNew: false,
    rating: 5.0,
    stock: 1,
    sold: 99,
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=600&auto=format&fit=crop",
    tags: ["Extreme Luxury"]
  },
  {
    id: 17,
    name: "Soft Pinch Blush",
    brand: "Rare Beauty",
    type: "Suyuq rumyona",
    category: "Makeup",
    description: "Selena Gomez'dan teringizga tabiiy va sog'lom rang beruvchi rumyona.",
    price: 23,
    oldPrice: 28,
    discount: 17,
    isNew: true,
    rating: 4.9,
    stock: 14,
    sold: 88,
    image: "https://images.unsplash.com/photo-1515688594390-b649af70d282?q=80&w=600&auto=format&fit=crop",
    tags: ["Viral"]
  },
  {
    id: 18,
    name: "Ultra Facial Cream",
    brand: "Kiehl's",
    type: "Yuz kremi",
    category: "Skin Care",
    description: "24 soat davomida terini chuqur namlovchi engil vaznli klassik krem.",
    price: 38,
    oldPrice: 45,
    discount: 15,
    isNew: false,
    rating: 4.8,
    stock: 30,
    sold: 40,
    image: "https://images.unsplash.com/photo-1611082236934-0938280c242e?q=80&w=600&auto=format&fit=crop",
    tags: ["Classic"]
  },
  {
    id: 19,
    name: "Leave-in Cond.",
    brand: "Ouai",
    type: "Soch spreyi",
    category: "Hair Care",
    description: "Sochlarni oson taraladigan va ipakdek yumshoq qiluvchi ko'p funksiyali sprey.",
    price: 30,
    oldPrice: 35,
    discount: 14,
    isNew: true,
    rating: 4.6,
    stock: 22,
    sold: 30,
    image: "https://images.unsplash.com/photo-1531233076846-433983377224?q=80&w=600&auto=format&fit=crop",
    tags: ["New"]
  },
  {
    id: 20,
    name: "2% BHA Liquid",
    brand: "Paula's Choice",
    type: "Eksfoliant",
    category: "Skin Care",
    description: "Terini o'lik hujayralardan tozalovchi va yuz rangini tekislovchi eng mashhur eksfoliant.",
    price: 34,
    oldPrice: 42,
    discount: 19,
    isNew: false,
    rating: 4.9,
    stock: 12,
    sold: 90,
    image: "https://images.unsplash.com/photo-1556228578-8c89e6afd557?q=80&w=600&auto=format&fit=crop",
    tags: ["Holy Grail", "AI Choice"]
  }
];

export default productData;