export const flowerProducts = [
  {
    id: 1,
    name: "Elegant White Roses",
    brand: "Zelo Flowers",
    type: "Premium Buket",
    category: "Roses",
    description: "Eng saralangan oq atirgullardan iborat bo'lgan, go'zallik va poklik timsoli premium guldasta.",
    price: 45,
    oldPrice: 60,
    discount: 25,
    isNew: false,
    rating: 4.9,
    stock: 12,
    sold: 140,
    image: "https://images.unsplash.com/photo-1561181286-d3efa7d55364?q=80&w=600&auto=format&fit=crop",
    tags: ["Trending", "AI Choice"]
  },
  {
    id: 2,
    name: "Royal Red Passion",
    brand: "Zelo Flowers",
    type: "Klassik Buket",
    category: "Roses",
    description: "Yorqin qizil rangli golland atirgullari. Muhabbat izhori uchun eng mukammal tanlov.",
    price: 55,
    oldPrice: 70,
    discount: 21,
    isNew: true,
    rating: 5.0,
    stock: 8,
    sold: 210,
    image: "https://images.unsplash.com/photo-1548622316-bfb0ffcf3032?q=80&w=600&auto=format&fit=crop",
    tags: ["Best Seller", "Trending"]
  },
  {
    id: 3,
    name: "Pink Dream Tulips",
    brand: "Local Garden",
    type: "Mavsumiy Buket",
    category: "Tulips",
    description: "Bahoriy kayfiyat bag'ishlovchi, nozik va nafis pushti rangli lola buketlari.",
    price: 25,
    oldPrice: 32,
    discount: 21,
    isNew: false,
    rating: 4.8,
    stock: 35,
    sold: 95,
    image: "https://images.unsplash.com/photo-1520763185298-1b434c919102?q=80&w=600&auto=format&fit=crop",
    tags: ["New Collection"]
  },
  {
    id: 4,
    name: "Luxury Orchid Box",
    brand: "Orchid Line",
    type: "Qutidagi Gullar",
    category: "Orchids",
    description: "Maxsus eksklyuziv quti ichiga joylashtirilgan uzoq muddat yashovchi hashamatli orxideya.",
    price: 120,
    oldPrice: 150,
    discount: 20,
    isNew: true,
    rating: 4.9,
    stock: 4,
    sold: 45,
    image: "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?q=80&w=600&auto=format&fit=crop",
    tags: ["Luxury", "AI Choice"]
  },
  {
    id: 5,
    name: "Sunshine Sunflowers",
    brand: "Eco Garden",
    type: "Yozgi Buket",
    category: "Sunflowers",
    description: "Quyosh kabi porloq va yorqin kayfiyat ulashuvchi haqiqiy kungaboqar guldastasi.",
    price: 30,
    oldPrice: 40,
    discount: 25,
    isNew: false,
    rating: 4.7,
    stock: 20,
    sold: 88,
    image: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?q=80&w=600&auto=format&fit=crop",
    tags: ["Trending"]
  },
  {
    id: 6,
    name: "Lavender Field Harmony",
    brand: "Provence",
    type: "Quritilgan Gullar",
    category: "Lavender",
    description: "Yoqimli ifor taratuvchi va yillar davomida solmaydigan tabiiy lavanda to'plami.",
    price: 22,
    oldPrice: 28,
    discount: 21,
    isNew: false,
    rating: 4.6,
    stock: 40,
    sold: 64,
    image: "https://images.unsplash.com/photo-1528183429752-a97d0bf99b5a?q=80&w=600&auto=format&fit=crop",
    tags: ["Best Seller"]
  },
  {
    id: 7,
    name: "Pure White Lilies",
    brand: "Zelo Flowers",
    type: "Aromatik Buket",
    category: "Lilies",
    description: "O'zining kuchli xushbo'y hidi va ulug'vor ko'rinishi bilan ajralib turuvchi oq liliyalar.",
    price: 38,
    oldPrice: 50,
    discount: 24,
    isNew: true,
    rating: 4.8,
    stock: 15,
    sold: 73,
    image: "https://images.unsplash.com/photo-1560717789-0ac7c58ac90a?q=80&w=600&auto=format&fit=crop",
    tags: ["New"]
  },
  {
    id: 8,
    name: "Hydrangea Cloud Mix",
    brand: "Elite Flora",
    type: "Katta Buket",
    category: "Hydrangea",
    description: "Moviy va havorang gortenziyalardan yig'ilgan, bulutni eslatuvchi yirik guldasta.",
    price: 65,
    oldPrice: 80,
    discount: 18,
    isNew: false,
    rating: 4.9,
    stock: 6,
    sold: 110,
    image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?q=80&w=600&auto=format&fit=crop",
    tags: ["AI Choice", "Trending"]
  },
  {
    id: 9,
    name: "Peony Sorbet Fantasy",
    brand: "Elite Flora",
    type: "Premium Buket",
    category: "Peonies",
    description: "Eng nafis va qimmatbaho hisoblangan, och pushti rangli pion guldastalari.",
    price: 85,
    oldPrice: 110,
    discount: 22,
    isNew: true,
    rating: 5.0,
    stock: 5,
    sold: 150,
    image: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?q=80&w=600&auto=format&fit=crop",
    tags: ["Luxury", "Viral"]
  },
  {
    id: 10,
    name: "Pastel Meadow Mix",
    brand: "Eco Garden",
    type: "Mikst Buket",
    category: "Mixed",
    description: "Ester, xrizantema va mayda gullardan iborat yovvoyi tabiat uslubidagi kompozitsiya.",
    price: 33,
    oldPrice: 42,
    discount: 21,
    isNew: false,
    rating: 4.7,
    stock: 25,
    sold: 92,
    image: "https://images.unsplash.com/photo-1533616688419-b7a585564566?q=80&w=600&auto=format&fit=crop",
    tags: ["Classic"]
  },
  {
    id: 11,
    name: "Golden Autumn Chrysanthemum",
    brand: "Local Garden",
    type: "Mavsumiy Buket",
    category: "Chrysanthemums",
    description: "Uzoq vaqt yangi saqlanuvchi, yorqin sariq va jigarrang xrizantemalar.",
    price: 28,
    oldPrice: 35,
    discount: 20,
    isNew: false,
    rating: 4.5,
    stock: 50,
    sold: 40,
    image: "https://images.unsplash.com/photo-1508784411316-02b8cd4d3a3a?q=80&w=600&auto=format&fit=crop",
    tags: ["Classic"]
  },
  {
    id: 12,
    name: "Sweet Carnation Hugs",
    brand: "Eco Garden",
    type: "Yumshoq Buket",
    category: "Carnations",
    description: "Har qanday vaziyat uchun mos keladigan, samimiylik ramzi bo'lgan chinnigullar.",
    price: 20,
    oldPrice: 25,
    discount: 20,
    isNew: false,
    rating: 4.6,
    stock: 30,
    sold: 55,
    image: "https://images.unsplash.com/photo-1589244159943-460088ed5c92?q=80&w=600&auto=format&fit=crop",
    tags: ["Budget Choice"]
  },
  {
    id: 13,
    name: "Crimson Gerbera Joy",
    brand: "Local Garden",
    type: "Yorqin Buket",
    category: "Gerberas",
    description: "Katta va yorqin rangli gerberalardan tashkil topgan quvnoq guldasta.",
    price: 24,
    oldPrice: 30,
    discount: 20,
    isNew: true,
    rating: 4.7,
    stock: 18,
    sold: 42,
    image: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?q=80&w=600&auto=format&fit=crop",
    tags: ["New"]
  },
  {
    id: 14,
    name: "Eustoma Softness Box",
    brand: "Zelo Flowers",
    type: "Qutidagi Gullar",
    category: "Eustoma",
    description: "Atirgulga o'xshash nozik, ammo o'ziga xos tuzilishga ega oq va binafsha eustomalar.",
    price: 50,
    oldPrice: 65,
    discount: 23,
    isNew: false,
    rating: 4.9,
    stock: 10,
    sold: 105,
    image: "https://images.unsplash.com/photo-1562613528-4d0856802a04?q=80&w=600&auto=format&fit=crop",
    tags: ["Best Seller"]
  },
  {
    id: 15,
    name: "Infinity Red Rose",
    brand: "Orchid Line",
    type: "Shisha Ichidagi Gul",
    category: "Roses",
    description: "Ertaklardagidek shisha kolba ichiga joylashtirilgan, 5 yilgacha solmaydigan jonli atirgul.",
    price: 75,
    oldPrice: 95,
    discount: 21,
    isNew: true,
    rating: 5.0,
    stock: 5,
    sold: 62,
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop",
    tags: ["Luxury", "Viral"]
  },
  {
    id: 16,
    name: "Rainbow Rose Extravaganza",
    brand: "Elite Flora",
    type: "Premium Buket",
    category: "Roses",
    description: "Maxsus texnologiya yordamida barglari kamalak rangida bo'yalgan noyob golland atirgullari.",
    price: 110,
    oldPrice: 140,
    discount: 21,
    isNew: false,
    rating: 4.8,
    stock: 3,
    sold: 38,
    image: "https://images.unsplash.com/photo-1533616567430-33c82d54df28?q=80&w=600&auto=format&fit=crop",
    tags: ["Extreme Luxury"]
  },
  {
    id: 17,
    name: "Spring Anemone Breath",
    brand: "Eco Garden",
    type: "Mavsumiy Buket",
    category: "Anemones",
    description: "Qora o'rtali va yorqin rangli bargli noodatiy anemona gullari to'plami.",
    price: 42,
    oldPrice: 50,
    discount: 16,
    isNew: true,
    rating: 4.7,
    stock: 7,
    sold: 29,
    image: "https://images.unsplash.com/photo-1574482620826-40685ca5ebd2?q=80&w=600&auto=format&fit=crop",
    tags: ["New Collection"]
  },
  {
    id: 18,
    name: "Violet Alstroemeria Wave",
    brand: "Local Garden",
    type: "Mikst Buket",
    category: "Alstroemeria",
    description: "Uzoq umr ko'ruvchi, mayda yoqimli xalli chiziqlarga ega alstromeriya guldastasi.",
    price: 35,
    oldPrice: 45,
    discount: 22,
    isNew: false,
    rating: 4.6,
    stock: 22,
    sold: 80,
    image: "https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?q=80&w=600&auto=format&fit=crop",
    tags: ["Trending"]
  },
  {
    id: 19,
    name: "Peach Calla Lilies",
    brand: "Orchid Line",
    type: "Minimalistik Buket",
    category: "Callas",
    description: "Yuqori estetik did egalari uchun mo'ljallangan qat'iy va nafis shaftoli rangli kallalar.",
    price: 70,
    oldPrice: 85,
    discount: 17,
    isNew: false,
    rating: 4.9,
    stock: 6,
    sold: 47,
    image: "https://images.unsplash.com/photo-1596436889106-be35e843f974?q=80&w=600&auto=format&fit=crop",
    tags: ["AI Choice"]
  },
  {
    id: 20,
    name: "Red Velvet Amaryllis",
    brand: "Elite Flora",
    type: "Premium Buket",
    category: "Amaryllis",
    description: "Katta baxmal bargli, qirollik saroylarini eslatuvchi yirik qizil amarillislar.",
    price: 90,
    oldPrice: 115,
    discount: 21,
    isNew: true,
    rating: 4.9,
    stock: 4,
    sold: 31,
    image: "https://images.unsplash.com/photo-1516283250883-fa53d8e13515?q=80&w=600&auto=format&fit=crop",
    tags: ["Luxury"]
  },
  {
    id: 21,
    name: "Sweet Daffodil Dance",
    brand: "Local Garden",
    type: "Mavsumiy Buket",
    category: "Daffodils",
    description: "Sariq va oq rangli, xushbo'y hidli klassik bahoriy nargis guldastasi.",
    price: 19,
    oldPrice: 24,
    discount: 20,
    isNew: false,
    rating: 4.4,
    stock: 45,
    sold: 120,
    image: "https://images.unsplash.com/photo-1550931440-c6574c84cfc2?q=80&w=600&auto=format&fit=crop",
    tags: ["Classic"]
  },
  {
    id: 22,
    name: "Blue Iris Dream",
    brand: "Eco Garden",
    type: "Nodir Buket",
    category: "Irises",
    description: "Tabiatda kam uchraydigan to'q ko'k va siyohrang bargli jozibador iris guldastasi.",
    price: 36,
    oldPrice: 44,
    discount: 18,
    isNew: false,
    rating: 4.8,
    stock: 12,
    sold: 66,
    image: "https://images.unsplash.com/photo-1550950158-d0d960dff51b?q=80&w=600&auto=format&fit=crop",
    tags: ["Trending"]
  },
  {
    id: 23,
    name: "Pink Astilbe Cloud",
    brand: "Zelo Flowers",
    type: "Egzotik Buket",
    category: "Astilbe",
    description: "Mayda patsimon barglardan iborat, guldastaga o'zgacha hajm va go'zallik beruvchi astilbe.",
    price: 48,
    oldPrice: 58,
    discount: 17,
    isNew: true,
    rating: 4.7,
    stock: 9,
    sold: 40,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=600&auto=format&fit=crop",
    tags: ["New Collection"]
  },
  {
    id: 24,
    name: "White Freesia Serenade",
    brand: "Orchid Line",
    type: "Xushbo'y Buket",
    category: "Freesia",
    description: "Parfumeriya olamida mashhur bo'lgan, ajoyib hid taratuvchi nozik oq freziyalar.",
    price: 40,
    oldPrice: 50,
    discount: 20,
    isNew: false,
    rating: 4.9,
    stock: 15,
    sold: 83,
    image: "https://images.unsplash.com/photo-1567606901991-07f6ee607c9f?q=80&w=600&auto=format&fit=crop",
    tags: ["AI Choice"]
  },
  {
    id: 25,
    name: "Imperial Protea King",
    brand: "Elite Flora",
    type: "Egzotik Buket",
    category: "Protea",
    description: "Janubiy Afrika o'rmonlaridan keltirilgan, ulkan va antiqa ko'rinishga ega qirollik proteasi.",
    price: 135,
    oldPrice: 165,
    discount: 18,
    isNew: true,
    rating: 5.0,
    stock: 2,
    sold: 19,
    image: "https://images.unsplash.com/photo-1510274356864-a41d78e332a0?q=80&w=600&auto=format&fit=crop",
    tags: ["Luxury", "Rare"]
  },
  {
    id: 26,
    name: "Delphinium Blue Sky",
    brand: "Zelo Flowers",
    type: "Baland Buket",
    category: "Delphinium",
    description: "Uzun poyali, havorang va ko'k gullar bilan qoplangan ulug'vor guldasta.",
    price: 52,
    oldPrice: 65,
    discount: 20,
    isNew: false,
    rating: 4.8,
    stock: 11,
    sold: 52,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=600&auto=format&fit=crop",
    tags: ["Trending"]
  },
  {
    id: 27,
    name: "Succulent Terrarium Eco",
    brand: "Eco Garden",
    type: "Tuvakdagi Kompozitsiya",
    category: "Succulents",
    description: "Shisha shar ichidagi tirik sukkulentlar va moxlardan iborat zamonaviy mini-ekotizim.",
    price: 29,
    oldPrice: 38,
    discount: 23,
    isNew: false,
    rating: 4.6,
    stock: 25,
    sold: 71,
    image: "https://images.unsplash.com/photo-1463936575829-25148e1db1b8?q=80&w=600&auto=format&fit=crop",
    tags: ["Best Seller"]
  },
  {
    id: 28,
    name: "Majestic Sunflower Giant",
    brand: "Local Garden",
    type: "Katta Buket",
    category: "Sunflowers",
    description: "Yirik va baland poyali, uyingizga iliqlik olib kiruvchi maxsus kungaboqarlar.",
    price: 32,
    oldPrice: 40,
    discount: 20,
    isNew: false,
    rating: 4.7,
    stock: 14,
    sold: 60,
    image: "https://images.unsplash.com/photo-1541256996761-85df2bf31644?q=80&w=600&auto=format&fit=crop",
    tags: ["Classic"]
  },
  {
    id: 29,
    name: "Cotton Candy Gypsophila",
    brand: "Eco Garden",
    type: "Uzoq Yashovchi Buket",
    category: "Gypsophila",
    description: "Havo kabi engil, rang-barang mayda gipsofilalardan tayyorlangan shirinliksimon guldasta.",
    price: 27,
    oldPrice: 34,
    discount: 20,
    isNew: true,
    rating: 4.9,
    stock: 20,
    sold: 130,
    image: "https://images.unsplash.com/photo-1618022325802-7e5e732d97a1?q=80&w=600&auto=format&fit=crop",
    tags: ["Viral", "AI Choice"]
  },
  {
    id: 30,
    name: "Premium Vintage Hydrangea",
    brand: "Elite Flora",
    type: "Nodir Buket",
    category: "Hydrangea",
    description: "Kuzgi vintage uslubidagi, och yashil va to'q binafsha rang aralashmasidan iborat gortenziya.",
    price: 58,
    oldPrice: 72,
    discount: 19,
    isNew: false,
    rating: 4.8,
    stock: 7,
    sold: 44,
    image: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?q=80&w=600&auto=format&fit=crop",
    tags: ["Trending"]
  }
];
